unstable_features = true
merge_imports = true
wrap_comments = true
condense_wildcard_suffixes = true
format_strings = true
empty_item_single_line = false
fn_single_line = false
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
