[package]
name = "demo"
version = "0.1.0"
authors = ["Matthew Boeh <m@mboeh.com>"]
publish = false
edition = "2018"

[dependencies]
stpyr = { path = "../stpyr" }
stpyr_curses = { path = "../stpyr_curses" }
fern = "*"
log = "*"
